version: "3.9"

x-app: &app
  build:
    context: .
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
    PGPASSWORD: password
  image: pokedex.io-dev:0.0.a
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  build: .
  volumes:
    - ./:/app:cached
    - ./log:/root/log:cached
    - ./.psqlrc:/root/.psqlrc:ro
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - packs-test:/app/public/packs-test
    - rails_cache:/app/tmp/cache
    - ssh-data:/ssh:ro
  environment:
    <<: *env
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    EDITOR: vim
    PSQL_HISTFILE: /root/log/.psql_history
    REDIS_HOST: redis
    REDIS_URL: redis://redis:6379/
    SSH_AUTH_SOCK: /ssh/auth/sock
    WEBPACK_DEV_SERVER_MANIFEST_HOST: webpack
    WEBPACK_DEV_SERVER_HOST: webpack
  depends_on:
    - db
    - redis

services:
  web:
    <<: *backend
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - ssh-data:/ssh:ro
    ports:
      - "3000:3000"
    depends_on:
      - db

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  webpack:
    <<: *app
    command: ./bin/webpack-dev-server --inline true
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: localhost:3035
    ports:
      - 3035:3035
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - packs-test:/app/public/packs-test

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_history:/var/log/psql_history
    ports:
      - 5432
    environment:
      <<: *env
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  postgres:
  postgres_history:
  bundle:
  redis:
  rails_cache:
  node_modules:
  packs:
  packs-test:
  ssh-data:
    external:
      name: ssh_data
